Fix typing and parser
cod-sushi/alkana.py pull request #10
Opened 2021-09-22 07:08 UTC by eggplants

#9から、型注釈部分、argparseの使用部分、変換方法の変更部分を持ってきました。

2021-09-22 07:19 UTC, eggplants commented
```bash
$ alkana
usage: alkana [-h] [-V] word
alkana: error: the following arguments are required: word
$ alkana -h
usage: alkana [-h] [-V] word

A tool to get the katakana reading of an alphabetical string

positional arguments:
  word           The alphabetical string you want to get the katakana reading

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  show program's version number and exit
$ alkana -V
alkana 0.0.1
$ alkana Hello,\ cod-san！
ハロー, コッド-サン！
```

2021-09-22 16:43 UTC, cod-sushi commented on alkana/main.py
> +        return sub(
https://github.com/cod-sushi/alkana.py/pull/9#discussion_r713626834
上記に回答ありがとうございました。
closedとなっていたのでこちらで続きのお話をさせてください。

今回提案してくださった、文章の中のすべての英単語を置き換えるというのは確実に需要のある機能だと思います。
ただ、get_kana関数はシンプルさを保つため、1英単語を1カタカナ単語に置き換えることを使命とする関数のままにしたいと考えています。
なので、これを`get_kana_for_sentence` といった新しい関数として定義いただけますか？
（あんまりピンとくる名前にできていないので、もっとよい名前があればぜひPRにてご提案ください）

コミットを本PRへ追加していただく形で構いません。

2021-09-22 16:43 UTC, cod-sushi commented on alkana/console.py
> +                        version='%(prog)s {}'.format('0.0.1'))
versionの記述について確認しました。
また動作確認結果もありがとうございます！

2021-09-22 16:43 UTC, cod-sushi commented on alkana/console.py
> +def parse_args(test=None):
見落としていたら申し訳ないのですが、このtestという引数はNone以外になることはあるのでしょうか？
ないのであれば、該当部分は削除いただきたく思います。
テストが必要なのであれば、お手数ですが、適切なテストの追加をお願いいたします。

2021-09-22 16:57 UTC, eggplants commented on alkana/console.py
> +def parse_args(test=None):
コマンドライン引数を与えて`parse_args`をテストしたいときに、testに引数を渡すとテストできます。

>テストが必要なのであれば、お手数ですが、適切なテストの追加をお願いいたします。

pytestのテストケースを追加します。

2021-09-22 16:57 UTC, eggplants commented on alkana/main.py
> +        return sub(
了解しました。

2021-10-03 20:54 UTC, cod-sushi requested changes
間が空いてしまいすみません。テストの追加ありがとうございます！
細かい点ですが最後に1点修正お願いいたします。

2021-10-03 20:54 UTC, cod-sushi commented on alkana/main.py
> +            str(sentence).lower())
ここのlowerは不要になると思いますので削除願います。

2021-10-03 21:00 UTC, cod-sushi commented on alkana/main.py
> +            str(sentence).lower())
すみません、上記のコメントは誤りです。正しくは下記となります。

`get_kana_for_sentence`と`get_kana`で、`data`辞書で英単語カナ変換を行うという意図の実装が繰り返されています。
お手数をおかけいたしますが保守性のため`get_kana_for_sentence`から`get_kana`を呼び出す形に変更するようお願いいたします。

2021-10-03 21:20 UTC, eggplants commented
```shellsession
$ cd test
$ python -m unittest *.py -q
usage: alkana [-h] [-V] word

A tool to get the katakana reading of an alphabetical string

positional arguments:
  word           The alphabetical string you want to get the katakana reading

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  show program's version number and exit
alkana 0.0.1
usage: alkana [-h] [-V] word
alkana: error: unrecognized arguments: world
usage: alkana [-h] [-V] word
alkana: error: the following arguments are required: word
----------------------------------------------------------------------
Ran 9 tests in 0.005s

OK
$
```

2021-10-06 15:28 UTC, zomysan reviewed
現在都合により開発作業に時間を割けないため、追加して頂いた関数に関するテストを当方にて作成することができません。
一度PRを戻させていただきます。

もし再度PR頂ける場合、機能およびコードを網羅する十分なテストを含めたPRを作成してください。
また、linterによる自動修正や、警告抑制のための変更は機能に影響しない部分なので、PRに含めないようお願いいたします。

レビューを迅速に行うためにもご協力お願いいたします。

2021-10-06 15:28 UTC, zomysan commented on alkana/main.py
> +            get_kana(sentence))
この変更で@eggplant氏の意図通りに動作するか判断しかねています。日本語混じりの文章をget_kanaに渡すとNoneが返ってくると思います。

2021-10-06 15:28 UTC, closed without merging